#+TITLE: Org-Coursepack
#+AUTHOR: Joon Ro

[[https://travis-ci.com/joonro/Org-Coursepack][https://travis-ci.com/joonro/Org-Coursepack.svg?branch=master]]

The Org-Coursepack provides a template for developing and managing teaching
materials using [[https://orgmode.org][Org mode]], a major mode in [[https://www.gnu.org/software/emacs/][GNU Emacs]].

Please see the [[https://joonro.github.io/Org-Coursepack/Lectures/01%20Course%20Introduction.html#quickstart-guide][quickstart guide]] for basic usage of =Org-Coursepack= with
screenshots.

The template (see =Courses/Template=) is designed to be self-explanatory, as
the documentation for it (see =Courses/Org-Coursepack=) consists of an example
course developed with this template. See the [[https://joonro.github.io/Org-Coursepack/][HTML version of the documentation]].

See [[file:paper.md]] for the detailed summary for the template.

* Dependencies
Using Org-Coursepack requires Emacs for creating course content and LaTeX for
exporting handouts. Follow the installation instructions below.
** Emacs 
See the official [[https://www.gnu.org/software/emacs/download.html][Download & installation]] page to learn how to install Emacs.
*** Emacs init file
The =Org-Coursepack= includes an example [[https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Init-file.html#Init-file][Emacs init file]] (located at
[[https://github.com/joonro/Org-Coursepack/blob/master/Assets/.emacs.d/init.el][/Assets/.emacs.d/init.el]] which has necessary settings for its basic usage
(e.g., package installations and export options). You can place the file
(=init.el=) into the =.emacs.d= directory under your =HOME= folder
(=~/.emacs.d/init.el=). See [[https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Location-of-init-file.html#Location-of-init-file][Where do I put my init file?]] of the Emacs
documentation for more details. (Note that, for Emacs to be able to locate the
init file in Windows, you must to add an environmental variable named =HOME=,
with the variable value set to your user profile directory (e.g.,
=C:\Users\UserName=). See [[https://java.com/en/download/help/path.xml][How do I set or change the PATH system variable?]] to
learn how to add environmental variables in Windows.)
 
Those already using Emacs would likely have an init file with their own custom
settings. They can copy and paste necessary codes from the example init file
(e.g., lines starting from ~;; * Org-Coursepack settings~) to their own init
file.

Note that the init file is set up to detect and install any necessary packages
(=htmlize=, =org-plus-contrib=, and =ox-reveal=) that are missing. This might
lengthen the startup time when the user runs Emacs for the first time.
** LaTeX
You can install [[https://tug.org/texlive/][TeX Live]] (for GNU/Linux and Windows) or [[https://tug.org/mactex/][MacTeX]] (for macOS).

* Installation of =Org-Coursepack=
=Org-Coursepack= can be installed by cloning the repo (=$ git clone
https://github.com/joonro/Org-Coursepack.git=) or by downloading and unzipping
the [[https://github.com/joonro/Org-Coursepack/archive/master.zip][ZIP archive]]. The Org-Coursepack is a self-contained package and thus will
work regardless of where it is installed; hence, users can freely choose the
location of the installation.

* Usage
We created the full documentation in the form of a short course. You can read
the [[https://joonro.github.io/Org-Coursepack/][HTML version of the documentation]] or take a look at [[https://github.com/joonro/Org-Coursepack/tree/master/Courses/Org-Coursepack/2018%2520Fall/Lectures][exported PDF files]].
* Example Courses
The Org-Coursepack includes two example courses created with Org-Coursepack:
=Introduction to Regression Analysis with Excel= and =Introduction to
Regression Analysis with Python=. These example courses showcase the modular
usage of the template, as they focus on how to reduce redundancy in creating
overalapping course materials.

The two courses share plenty of materials in statistical topics, but one
course applies these topics using Excel while the other uses
Python. Demonstrating how to efficiently construct course materials with the
Org-Coursepack, the courses share materials on statistical topics via topic
Org files and selectively include materials related to Python and Excel from
their own respective topic Org files where needed.

See the semester Org files, exported syllabus, and exported lecture files
linked below.
** Introduction to Regression Analysis with Excel
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Excel/2018%20Fall/2018%20Fall.org][Semester Org file (Fall 2018)]]
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Excel/2018%20Fall/Syllabus/Syllabus%20(Section%201).pdf][Exported Syllabus]]
- [[https://github.com/joonro/Org-Coursepack/tree/master/Courses/Intro-Regression-Excel/2018%20Fall/Lectures][Exported Lecture files]]

** Introduction to Regression Analysis with Python
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Python/2018%20Fall/2018%20Fall.org][Semester Org file (Fall 2018)]]
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Python/2018%20Fall/Syllabus/Syllabus%20(Section%201).pdf][Exported Syllabus]]
- [[https://github.com/joonro/Org-Coursepack/tree/master/Courses/Intro-Regression-Python/2018%20Fall/Lectures][Exported Lecture files]]
* Authors
- [[https://github.com/joonro/Org-Coursepack/tree/develop/Courses/Intro-Regression-Excel/2018%2520Fall/Lectures][Joon H. Ro]] & [[https://github.com/namkoong80][Jae Eun Namkoong]]
* Changelog
** v1.1.0
- Add two example courses, =Introduction to Regression Analysis with Excel=
  and =Introduction to Regression Analysis with Python=
