#+TITLE: Org-Coursepack
#+AUTHOR: Joon Ro
The Org-Coursepack provides a template for developing and managing teaching
materials using [[https://orgmode.org][Org mode]], a major mode in [[https://www.gnu.org/software/emacs/][GNU Emacs]]. The template is designed
to be self-explanatory, as the documentation for it consists of an example
course developed with this template.

The template (see =Courses/Template=) is designed to be self-explanatory, as
the documentation for it (see =Courses/Org-Coursepack=) consists of an example
course developed with this template.

See [[file:paper.md]] for the detailed summary for the template.
* Dependencies
- [[https://www.gnu.org/software/emacs/][GNU Emacs]] (Org mode is distributed as part of the Emacs)
- [[https://github.com/yjwen/org-reveal/][Org-Reveal]] (to create [[https://revealjs.com/#/][Reveal.js]] slides)
- LaTeX (to create LaTeX handouts or Beamer slides)
* Installation
Clone the repo or download the ZIP archive.
* Usage
Org-Coursepack consists of multiple Org files. We created the documentation in
the form of a short course. You can read the [[https://joonro.github.io/Org-Coursepack/][HTML version of the documentation]]
or checkout exported PDF files in =Org-Coursepack/Courses/Org-Coursepack/2018
Fall/Lectures/=.
* Example Courses
The Org-Coursepack includes two example courses created with Org-Coursepack
: =Introduction to Regression Analysis with Excel= and =Introduction to
Regression Analysis with Python=. These example courses showcase the modular
usage of the template, as they focus on how to reduce redundancy in creating
overalapping course materials.

The two example courses share plenty of materials in statistical topics, but
one course applies these topics using Excel while the other uses Python. The
example courses share materials on fundamental statistical topics via topic
Org files and selectively include materials related to Python and Excel from
their own respective topic Org files where needed, demonstrating how to
efficiently construct course materials with the Org-Coursepack,

See the semester Org files, exported syllabus, and exported lecture files
linked below.
** Introduction to Regression Analysis with Excel
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Excel/2018%2520Fall/2018%2520Fall.org][Semester Org file (Fall 2018)]]
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Excel/2018%2520Fall/Syllabus/Syllabus%2520(Section%25201).pdf][Exported Syllabus]]
- [[https://github.com/joonro/Org-Coursepack/tree/master/Courses/Intro-Regression-Excel/2018%2520Fall/Lectures][Exported Lecture files directory]]

** Introduction to Regression Analysis with Python
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Python/2018%2520Fall/2018%2520Fall.org][Semester Org file (Fall 2018)]]
- [[https://github.com/joonro/Org-Coursepack/blob/master/Courses/Intro-Regression-Python/2018%2520Fall/Syllabus/Syllabus%2520(Section%25201).pdf][Exported Syllabus]]
- [[https://github.com/joonro/Org-Coursepack/tree/master/Courses/Intro-Regression-Python/2018%2520Fall/Lectures][Exported Lecture files directory]]
* Authors
- [[https://github.com/joonro/Org-Coursepack/tree/develop/Courses/Intro-Regression-Excel/2018%2520Fall/Lectures][Joon Ro]] & Jae Eun Namkoong
* Changelog
** v1.1.0
- Add two example courses, =Introduction to Regression Analysis with Excel=
  and =Introduction to Regression Analysis with Python=
